name: deploy

on:
  workflow_dispatch:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install
        run: npm i

      - name: Build
        run: npm run build
  
      - name: Save Artifact Build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/
          retention-days: 1
  
      - name: Save Artifact Assets
        uses: actions/upload-artifact@v3
        with:
          name: assets
          path: assets/
          retention-days: 1

  build_vue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Build
        run: |
          cd ./vuepress-starter/
          npm i
          npm run docs:build
      - name: Save Artifact Build
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./vuepress-starter/docs/.vuepress/dist/
          retention-days: 1
  
  deploy_win:
    runs-on: docs-en-deploy
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Copy artifacts
        run: |
          cp -Recurse -Force ./build/site/* c:/inetpub/wwwroot/docs/en/
          cp -Recurse -Force ./assets/* c:/inetpub/wwwroot/docs/ -Exclude @("site")
          
  deploy_docs_bastyon_com:
    runs-on: docs.bastyon.com
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Copy artifacts
        run: |
          cp -r ./build/site/* /data/docs/en/
          cp -r ./assets/* /data/docs/

  deploy_docs_pocketnet_app:
    runs-on: docs.bastyon.com
    needs: build_vue
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Copy artifacts
        run: |
          rm -rf /data/documentation/*
          cp -r ./dist/* /data/documentation/