name: deploy

on:
  workflow_dispatch:
  push:

jobs:

  build_vue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Build
        run: |
          npm i
          npm run docs:build
      - name: Save Artifact Build
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./vuepress-starter/docs/.vuepress/dist/
          retention-days: 1

  # deploy_docs_bastyon_com:
  #   runs-on: docs.bastyon.com
  #   needs: build_vue
  #   steps:
  #     - name: Download artifacts
  #       uses: actions/download-artifact@v4
  #     - name: Copy artifacts
  #       run: |
  #         rm -rf /data/docs/*
  #         cp -r ./dist/* /data/docs/

  deploy_docs_pocketnet_app:
    runs-on: docs.bastyon.com
    needs: build_vue
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Copy artifacts
        run: |
          rm -rf /data/documentation/*
          cp -r ./dist/* /data/documentation/
